FROM centos:7

# Install Ansible Runner
RUN yum -y update && yum -y install epel-release  && \
    yum -y install ansible python-psutil python-pip bubblewrap bzip2 python-crypto \
                   which gcc python-devel libxml2 libxml2-devel krb5 krb5-devel curl curl-devel \
                   openssh openssh-clients
RUN pip install python-memcached wheel pexpect psutil python-daemon pipenv setuptools

RUN localedef -c -i en_US -f UTF-8 en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ADD https://github.com/krallin/tini/releases/download/v0.14.0/tini /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--"]
WORKDIR /
