[tox]
env_list =
    linters
    unit
    integration
requires =
    tox>4
    setuptools>=64

[shared]
pytest_cov_args = --cov --cov-report html --cov-report term --cov-report xml

[testenv]
description = Run tests with {basepython}
deps =
    !devel: ansible-core
    {unit,integration}-devel: ansible-core @ https://github.com/ansible/ansible/archive/devel.tar.gz
    -r {toxinidir}/test/requirements.txt
passenv =
    HOME
    RUNNER_TEST_IMAGE_NAME
usedevelop = True
commands = pytest -vv -n auto {posargs}

[testenv:linters{,-py310,-py311,-py312,-py313,-py314}]
description = Run code linters
commands =
    flake8 --version
    flake8 docs src/ansible_runner test
    yamllint --version
    yamllint -s .
    mypy src/ansible_runner
    pylint src/ansible_runner test

[testenv:unit{,-py310,-py311,-py312,-py313,-py314,-devel}]
description = Run unit tests
commands =
    pytest test/unit -vv -n auto {[shared]pytest_cov_args} {posargs}

[testenv:integration{,-py310,-py311,-py312,-py313,-py314,-devel}]
description = Run integration tests
commands =
    pytest test/integration -vv -n auto {[shared]pytest_cov_args} {posargs}

[testenv:docs]
description = Build documentation
deps = -r{toxinidir}/docs/requirements.txt
commands =
    sphinx-build -T -E -W -n --keep-going {tty:--color} -j auto -d docs/build/doctrees -b html docs docs/build/html

[testenv:clean]
description = Erase docs and coverage artifacts
skip_install = True
base =
allowlist_externals = /bin/sh
commands =
    /bin/sh -c "rm -rf {toxinidir}/test/coverage/*"
    /bin/sh -c "rm -rf {toxinidir}/docs/{_,}build"

# flake8 config not supported in pyproject.toml, so... yeah
[flake8]
# W503 - Line break occurred before a binary operator
ignore = W503
max-line-length = 160
per-file-ignores =
    src/ansible_runner/display_callback/callback/awx_display.py:E402
