---
- hosts: all
  tasks:
    - name: Setup ensure-docker role
      include_role:
        name: ensure-docker

    - name: Setup use-buildset-registry role
      include_role:
        name: use-buildset-registry

    - name: pull docker image
      shell: docker pull quay.io/ansible/ansible-runner:devel
