FROM centos:8

RUN dnf install -y epel-release
RUN yum install -y make mock python3-pip which git

# Newer version of setuptools needed for pipenv
RUN pip3 install -IU pip setuptools
RUN pip3 install -IU pipenv ansible
