---
- project:
    check:
      jobs: &id001
        - ansible-runner-build-container-image
        - ansible-runner-build-container-image-stable-2.9
        - ansible-runner-build-container-image-stable-2.10
        - ansible-runner-build-container-image-stable-2.11
        - ansible-tox-py36
        - ansible-tox-py37
    gate:
      jobs: *id001
