---
- project:
    check:
      jobs: &id001
        - ansible-buildset-registry
        - ansible-runner-build-container-image-stable-2.9
        - ansible-runner-build-container-image-stable-2.10
        - ansible-runner-build-container-image-stable-2.11
        - ansible-runner-build-container-image-stable-2.12
    gate:
      jobs: *id001
    post:
      jobs: &id002
        - ansible-buildset-registry
        - ansible-runner-upload-container-image-stable-2.9:
            vars:
              upload_container_image_promote: false
        - ansible-runner-upload-container-image-stable-2.10:
            vars:
              upload_container_image_promote: false
        - ansible-runner-upload-container-image-stable-2.11:
            vars:
              upload_container_image_promote: false
        - ansible-runner-upload-container-image-stable-2.12:
            vars:
              upload_container_image_promote: false
    periodic:
      jobs: *id002
