name: Label

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  issues:
    types:
      - opened
      - reopened

  pull_request:
    types:
      - opened
      - reopened

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Triage

    steps:
      - name: Apply labels
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
